# Generated by Django 5.0.6 on 2024-06-27 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interviewee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorite_programming_language", models.CharField(max_length=50)),
                ("interview_date", models.CharField(max_length=50)),
            ],
        ),
    ]
