# Generated by Django 5.0.6 on 2024-06-27 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewee",
            name="name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="interviewee",
            name="willing_to_use_ruby",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interviewee",
            name="willing_to_work_onsite",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interviewee",
            name="years_of_experience",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="interviewee",
            name="favorite_programming_language",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="interviewee",
            name="interview_date",
            field=models.CharField(default="", max_length=50),
        ),
    ]
