# Generated by Django 5.0.6 on 2024-06-27 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("interview", "0002_interviewee_name_interviewee_willing_to_use_ruby_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewee",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
